import Foundation
import GRDB

actor CorpusWriter {
    enum WriteResult: Equatable {
        case inserted, exactDuplicate, alreadyIngested, selfGenerated
        /// An existing row whose source file changed content was updated in
        /// place (documents only — see `updateChanged` on `writeBatch`).
        case updated
    }

    private let db: AppDatabase

    init(db: AppDatabase) {
        self.db = db
    }

    nonisolated private func _sourceIDSync(for kind: SourceKind, in writer: any DatabaseWriter) throws -> Int64 {
        try writer.write { dbc in
            if let existing = try Source.filter(Column("kind") == kind.rawValue).fetchOne(dbc),
               let id = existing.id {
                return id
            }
            var source = Source(id: nil, kind: kind.rawValue, configJson: "{}", lastSyncedAt: nil)
            try source.insert(dbc)
            return source.id!
        }
    }

    func sourceID(for kind: SourceKind) async throws -> Int64 {
        try _sourceIDSync(for: kind, in: db.writer)
    }

    nonisolated private func _accountIDSync(for hint: String, in writer: any DatabaseWriter) throws -> Int64 {
        try writer.write { dbc in
            if let existing = try Account
                .filter(Column("address_or_handle") == hint).fetchOne(dbc),
               let id = existing.id {
                return id
            }
            var account = Account(id: nil, addressOrHandle: hint)
            try account.insert(dbc)
            return account.id!
        }
    }

    func accountID(for hint: String) async throws -> Int64 {
        try _accountIDSync(for: hint, in: db.writer)
    }

    nonisolated private func _setOwnAddressesSync(json: String, id: Int64, in writer: any DatabaseWriter) throws {
        try writer.write { dbc in
            try dbc.execute(sql: "UPDATE accounts SET addresses_json = ? WHERE id = ?",
                            arguments: [json, id])
        }
    }

    func setOwnAddresses(_ addresses: [String], accountHint: String) async throws {
        let id = try await accountID(for: accountHint)
        let json = String(data: try JSONEncoder().encode(addresses), encoding: .utf8) ?? "[]"
        try _setOwnAddressesSync(json: json, id: id, in: db.writer)
    }

    /// Two-column probe for the external-id dedupe check. Re-ingest ("Ingest
    /// All" over an already-ingested corpus) is dominated by this skip path,
    /// and a full-record fetch would drag every already-stored message body
    /// (raw_text + clean_text) back out of SQLite once per skip. Only id and
    /// drop_reason are ever needed to route the skip.
    private struct ExistingProbe: FetchableRecord {
        let id: Int64
        let dropReason: String?
        let sha256: String?
        init(row: Row) {
            id = row["id"]
            dropReason = row["drop_reason"]
            sha256 = row["sha256"]
        }
    }

    nonisolated private func _writeSync(_ raw: RawItem, sourceID: Int64, accountID: Int64?, hash: String, in writer: any DatabaseWriter) throws -> WriteResult {
        return try writer.write { dbc in
            try _writeBody(raw, sourceID: sourceID, accountID: accountID, hash: hash, dbc: dbc)
        }
    }

    /// One item's full dedupe/upgrade/insert logic against an open
    /// connection — shared verbatim by the single-item `write` (one
    /// transaction per item) and `writeBatch` (one transaction per chunk).
    nonisolated private func _writeBody(_ raw: RawItem, sourceID: Int64, accountID: Int64?, hash: String,
                                        updateChanged: Bool = false, dbc: Database) throws -> WriteResult {
        do {
            if let existing = try ExistingProbe.fetchOne(dbc, sql: """
                SELECT id, drop_reason, sha256 FROM items
                WHERE source_id = ? AND external_id = ?
                """, arguments: [sourceID, raw.externalID]) {
                // A message previously dropped as body_not_downloaded (partial
                // download at the time) can later be re-ingested once Mail has
                // fetched the full body. Upgrade the row in place instead of
                // permanently blocking it via the alreadyIngested short-circuit.
                if existing.dropReason == "body_not_downloaded", !raw.rawText.isEmpty {
                    // Before upgrading, apply the same guards as fresh inserts
                    // Self-ingestion guard (§7): check if this sha256 was generated by us
                    let recipients = String(
                        data: (try? JSONEncoder().encode(raw.recipients)) ?? Data("[]".utf8),
                        encoding: .utf8) ?? "[]"
                    if try Int.fetchOne(dbc,
                        sql: "SELECT COUNT(*) FROM generations WHERE sha256 = ?",
                        arguments: [hash]) ?? 0 > 0 {
                        try dbc.execute(sql: """
                            UPDATE items SET raw_text = ?, sha256 = ?, recipients_json = ?,
                                             state = 'filtered_out', drop_reason = 'self_generated',
                                             clean_text = NULL, simhash64 = NULL
                            WHERE id = ?
                            """, arguments: [raw.rawText, hash, recipients, existing.id])
                        return .selfGenerated
                    }
                    // Exact-duplicate guard: another row already holds this
                    // content (any state — see the insert path's guard).
                    if try Item.filter(Column("sha256") == hash
                                       && Column("raw_text") != ""
                                       && Column("id") != existing.id).fetchCount(dbc) > 0 {
                        // Leave the existing dropped row as-is; don't create a duplicate
                        return .exactDuplicate
                    }
                    // All guards passed; upgrade the row
                    try dbc.execute(sql: """
                        UPDATE items SET raw_text = ?, sha256 = ?, recipients_json = ?,
                                         state = 'ingested', drop_reason = NULL,
                                         clean_text = NULL, simhash64 = NULL
                        WHERE id = ?
                        """, arguments: [raw.rawText, hash, recipients, existing.id])
                    return .inserted
                }
                // Edited-in-place source (documents: same path, new content).
                // Only when the caller opts in — messages are immutable, so
                // for them a same-ID/different-content pair means a parser
                // change, not an edit, and the original must win. The row is
                // updated in place with every derived field reset, so the
                // clean/filter/label passes re-process it as new text.
                if updateChanged, let oldHash = existing.sha256, oldHash != hash,
                   !raw.rawText.isEmpty {
                    let recipients = String(
                        data: (try? JSONEncoder().encode(raw.recipients)) ?? Data("[]".utf8),
                        encoding: .utf8) ?? "[]"
                    if try Int.fetchOne(dbc,
                        sql: "SELECT COUNT(*) FROM generations WHERE sha256 = ?",
                        arguments: [hash]) ?? 0 > 0 {
                        try dbc.execute(sql: """
                            UPDATE items SET raw_text = ?, sha256 = ?, recipients_json = ?,
                                             state = 'filtered_out', drop_reason = 'self_generated',
                                             clean_text = NULL, simhash64 = NULL
                            WHERE id = ?
                            """, arguments: [raw.rawText, hash, recipients, existing.id])
                        return .selfGenerated
                    }
                    // New content duplicates another item — keep the stored
                    // version rather than creating a same-text twin.
                    if try Item.filter(Column("sha256") == hash
                                       && Column("raw_text") != ""
                                       && Column("id") != existing.id).fetchCount(dbc) > 0 {
                        return .exactDuplicate
                    }
                    try dbc.execute(sql: """
                        UPDATE items SET raw_text = ?, sha256 = ?, recipients_json = ?,
                                         authored_at = ?, date_confidence = ?,
                                         state = 'ingested', drop_reason = NULL,
                                         clean_text = NULL, simhash64 = NULL,
                                         word_count = NULL, lang = NULL,
                                         mode = NULL, label_source = NULL,
                                         quality_score = NULL
                        WHERE id = ?
                        """, arguments: [raw.rawText, hash, recipients,
                                         raw.authoredAt,
                                         raw.authoredAtConfidence?.rawValue,
                                         existing.id])
                    return .updated
                }
                // Backfill (spec §2): the same message re-parsed by a later
                // "Ingest All" now carries reply context that the original
                // ingest predates, and/or an authored_at the old strict
                // export-date parse dropped (~13% of sms). Fill each in
                // exactly once — COALESCE keeps stored values, and the WHERE
                // clause only touches the row when there is genuinely
                // something to fill (idempotent, never destructive, and no
                // no-op row rewrite on the common skip). A deleted
                // conversation whose skip never fires again simply keeps a
                // NULL context.
                if raw.contextText != nil || raw.authoredAt != nil {
                    try dbc.execute(sql: """
                        UPDATE items SET context_text = COALESCE(context_text, ?),
                                         authored_at = COALESCE(authored_at, ?)
                        WHERE id = ? AND ((context_text IS NULL AND ? IS NOT NULL)
                                       OR (authored_at IS NULL AND ? IS NOT NULL))
                        """, arguments: [raw.contextText, raw.authoredAt, existing.id,
                                         raw.contextText, raw.authoredAt])
                }
                return .alreadyIngested
            }
            var item = Self.makeItem(from: raw, sourceID: sourceID,
                                     accountID: accountID, hash: hash)
            item.contextText = raw.contextText
            // Self-ingestion guard (§7): live from the first ingest.
            if try Int.fetchOne(dbc,
                sql: "SELECT COUNT(*) FROM generations WHERE sha256 = ?",
                arguments: [hash]) ?? 0 > 0 {
                item.state = "filtered_out"
                item.dropReason = "self_generated"
                try item.insert(dbc)
                return .selfGenerated
            }
            // Any row with this content — INCLUDING pass-filtered ones —
            // makes the incoming item a duplicate. Excluding dropped rows
            // here made every filtered-out message re-insert (and be
            // re-filtered) on each ingest whose external id didn't line up.
            // Empty-raw rows (partial downloads) are excluded: their shared
            // empty-string hash says nothing about identity.
            if try Item.filter(Column("sha256") == hash
                               && Column("raw_text") != "").fetchCount(dbc) > 0 {
                return .exactDuplicate
            }
            try item.insert(dbc)
            return .inserted
        }
    }

    /// The one place a RawItem becomes an Item row — `_writeBody` and
    /// `writeDropped` previously each hand-built near-identical 20-field
    /// initializers that could drift apart.
    nonisolated private static func makeItem(from raw: RawItem, sourceID: Int64,
                                             accountID: Int64?, hash: String) -> Item {
        let recipients = String(
            data: (try? JSONEncoder().encode(raw.recipients)) ?? Data("[]".utf8),
            encoding: .utf8) ?? "[]"
        return Item(
            id: nil, sourceId: sourceID, accountId: accountID,
            externalId: raw.externalID, kind: raw.kind.rawValue,
            authoredAt: raw.authoredAt, recipientsJson: recipients,
            threadId: raw.threadID, rawText: raw.rawText, cleanText: nil,
            wordCount: nil, lang: nil, sha256: hash, simhash64: nil,
            provenance: "native", state: "ingested", dropReason: nil,
            medium: nil, audience: nil, mode: nil, labelSource: nil,
            qualityScore: nil,
            dateConfidence: raw.authoredAtConfidence?.rawValue)
    }

    func write(_ raw: RawItem, sourceID: Int64, accountID: Int64?) async throws -> WriteResult {
        let hash = sha256Hex(canonicalize(raw.rawText))
        return try _writeSync(raw, sourceID: sourceID, accountID: accountID, hash: hash, in: db.writer)
    }

    /// Batched ingest writes: identical per-item semantics to `write`, but
    /// one transaction per `chunkSize` items instead of one per item —
    /// bulk ingest (and re-ingest, which is dominated by dedupe probes)
    /// was paying thousands of tiny commits. Chunked rather than one giant
    /// transaction so a mid-run cancel loses at most one chunk of progress,
    /// preserving the resumable-cancel contract.
    func writeBatch(_ raws: [RawItem], sourceID: Int64, accountID: Int64?,
                    chunkSize: Int = 250,
                    updateChanged: Bool = false) async throws -> [WriteResult] {
        try await writeBatch(raws, sourceID: sourceID,
                             accountIDs: Array(repeating: accountID, count: raws.count),
                             chunkSize: chunkSize, updateChanged: updateChanged)
    }

    /// Per-item-account variant of `writeBatch` — mail items resolve their
    /// account from each message's From header, so a single batch spans
    /// accounts. `accountIDs` must align 1:1 with `raws`. `updateChanged`
    /// opts into updating an existing row in place when the same external
    /// ID arrives with different content (edited documents); leave false
    /// for immutable sources like messages and mail.
    func writeBatch(_ raws: [RawItem], sourceID: Int64, accountIDs: [Int64?],
                    chunkSize: Int = 250,
                    updateChanged: Bool = false) async throws -> [WriteResult] {
        precondition(raws.count == accountIDs.count)
        var results: [WriteResult] = []
        results.reserveCapacity(raws.count)
        var start = 0
        while start < raws.count {
            try Task.checkCancellation()
            let end = min(start + chunkSize, raws.count)
            results += try _writeChunkSync(Array(raws[start..<end]),
                                           sourceID: sourceID,
                                           accountIDs: Array(accountIDs[start..<end]),
                                           updateChanged: updateChanged,
                                           in: db.writer)
            start += chunkSize
        }
        return results
    }

    nonisolated private func _writeChunkSync(_ raws: [RawItem], sourceID: Int64,
                                             accountIDs: [Int64?],
                                             updateChanged: Bool,
                                             in writer: any DatabaseWriter) throws -> [WriteResult] {
        let hashes = raws.map { sha256Hex(canonicalize($0.rawText)) }
        return try writer.write { dbc in
            try zip(zip(raws, hashes), accountIDs).map { pair, accountID in
                try _writeBody(pair.0, sourceID: sourceID, accountID: accountID,
                               hash: pair.1, updateChanged: updateChanged, dbc: dbc)
            }
        }
    }

    /// External IDs this source has already recorded — ingestors check the
    /// set BEFORE the expensive stages (full MIME parse, actor hop, dedupe
    /// probe), turning a re-ingest into a header-read-and-skip pass.
    /// Partial rows ("body_not_downloaded") are excluded so a message whose
    /// body has since downloaded still gets its real ingest; the write-side
    /// content-hash dedupe stays authoritative either way.
    func knownExternalIDs(sourceID: Int64) async throws -> Set<String> {
        try await db.writer.read { dbc in
            Set(try String.fetchAll(dbc, sql: """
                SELECT external_id FROM items
                WHERE source_id = ?
                  AND (drop_reason IS NULL OR drop_reason <> 'body_not_downloaded')
                """, arguments: [sourceID]))
        }
    }

    nonisolated private func _markSyncedSync(sourceID: Int64, in writer: any DatabaseWriter) throws {
        try writer.write { dbc in
            try dbc.execute(sql: "UPDATE sources SET last_synced_at = ? WHERE id = ?",
                            arguments: [Date(), sourceID])
        }
    }

    func markSynced(sourceID: Int64) async throws {
        try _markSyncedSync(sourceID: sourceID, in: db.writer)
    }

    nonisolated private func _writeDroppedSync(_ raw: RawItem, sourceID: Int64, accountID: Int64?,
                                               dropReason: String, in writer: any DatabaseWriter) throws {
        try writer.write { dbc in
            if try Item.filter(Column("source_id") == sourceID
                               && Column("external_id") == raw.externalID)
                .fetchCount(dbc) > 0 { return }
            var item = Self.makeItem(from: raw, sourceID: sourceID, accountID: accountID,
                                     hash: sha256Hex(canonicalize(raw.rawText)))
            item.state = "filtered_out"
            item.dropReason = dropReason
            try item.insert(dbc)
        }
    }

    func writeDropped(_ raw: RawItem, sourceID: Int64, accountID: Int64?,
                      dropReason: String) async throws {
        try _writeDroppedSync(raw, sourceID: sourceID, accountID: accountID,
                              dropReason: dropReason, in: db.writer)
    }

    // MARK: - Mbox fingerprints
    //
    // A "Ingest All" that re-parses an unchanged multi-gigabyte Sent Mail
    // mbox purely to dedupe-skip every message is a real time sink. These
    // fingerprints let an ingestor skip the whole file in one stat() call
    // when it hasn't changed since it was last fully processed. `CorpusReset`
    // clears them (see CorpusReset.swift) so a reset corpus doesn't skip
    // every mbox on re-ingest and land nothing.

    /// Shared settings access for ingestors that read ingest-time options
    /// (e.g. the Documents type toggles) without holding the database
    /// themselves.
    var settingsStore: SettingsStore { SettingsStore(db: db) }

    /// Key prefix says "mbox" for historical reasons (transcripts adopted
    /// the same mechanism later) — kept so existing stored fingerprints and
    /// CorpusReset's prefix-clear stay valid.
    private func fingerprintKey(forFilePath path: String) -> String {
        "mbox.fingerprint." + sha256Hex(path)
    }

    /// The stored "size:mtimeEpoch" fingerprint for `path`, if any.
    func fileFingerprint(path: String) async throws -> String? {
        try await SettingsStore(db: db).get(fingerprintKey(forFilePath: path))
    }

    /// Records `path`'s current size/mtime as its fingerprint. Callers must
    /// only call this AFTER the mbox has been fully processed without
    /// cancellation — a cancelled run must re-read the file next time.
    func setFileFingerprint(path: String, size: Int, mtimeEpoch: Int) async throws {
        try await setFileFingerprint(path: path, value: "\(size):\(mtimeEpoch)")
    }

    /// Raw-value variant for fingerprints that aren't size:mtime shaped
    /// (e.g. Apple Mail's per-mailbox file-listing fingerprints).
    func setFileFingerprint(path: String, value: String) async throws {
        try await SettingsStore(db: db).set(fingerprintKey(forFilePath: path), value)
    }

    /// Batched fingerprint writes — one transaction for a whole flush's
    /// worth of documents instead of one settings commit per file.
    func setFileFingerprints(_ entries: [(path: String, value: String)]) async throws {
        guard !entries.isEmpty else { return }
        let rows = entries.map { (fingerprintKey(forFilePath: $0.path), $0.value) }
        try await db.writer.write { dbc in
            for (key, value) in rows {
                try dbc.execute(sql: """
                    INSERT INTO settings (key, value) VALUES (?, ?)
                    ON CONFLICT(key) DO UPDATE SET value = excluded.value
                    """, arguments: [key, value])
            }
        }
    }
}
